import{NextRequest,NextResponse}from'next/server';import{createClient,createServiceClient}from'@/lib/supabase-server';import{z}from'zod';
const patchSchema=z.object({action:z.enum(['cancel','status','archive']),status:z.enum(['confirmed','completed','no_show','cancelled']).optional(),reason:z.string().trim().max(500).optional()});
async function authorized(id:string){const auth=await createClient(),{data:{user}}=await auth.auth.getUser();if(!user)return null;const db=createServiceClient(),{data:ap}=await db.from('appointments').select('*,services(name),businesses(name,phone)').eq('id',id).single();if(!ap)return null;const{data:member}=await auth.from('business_members').select('business_id').eq('business_id',ap.business_id).eq('user_id',user.id).maybeSingle();return member?{db,ap}:null}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const{id}=await params,x=patchSchema.parse(await req.json()),ctx=await authorized(id);if(!ctx)return NextResponse.json({error:'Yetkiniz yok.'},{status:403});const{db,ap}=ctx;if(x.action==='cancel'){const reason=x.reason||'İşletme tarafından iptal edildi.',now=new Date().toISOString(),{error}=await db.from('appointments').update({status:'cancelled',cancellation_reason:reason,cancelled_at:now,updated_at:now}).eq('id',id);if(error)return NextResponse.json({error:'İptal edilemedi.'},{status:500});await sendCancellation(ap,reason);return NextResponse.json({ok:true,whatsappUrl:whatsapp(ap,reason)})}if(x.action==='archive'){await db.from('appointments').update({archived_at:new Date().toISOString()}).eq('id',id);return NextResponse.json({ok:true})}const statusUpdate:any={status:x.status,updated_at:new Date().toISOString()};if(x.status==='completed'){
      const now=new Date(),originalStart=new Date(ap.start_at),originalEnd=new Date(ap.end_at);
      if(now<originalStart){
        // İleri tarihli randevu erkenden/yerinde tamamlandı (örn. müşteri uğrayıp işini hemen yaptırdı) -
        // kaydı şimdiye taşıyoruz ki asıl (ileri tarihli) randevu saati anında boşalsın.
        statusUpdate.start_at=now.toISOString();
        statusUpdate.end_at=new Date(now.getTime()+5*60000).toISOString();
      }else if(now<originalEnd){
        statusUpdate.end_at=now.toISOString();
      }
    }await db.from('appointments').update(statusUpdate).eq('id',id);return NextResponse.json({ok:true})}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){const{id}=await params,ctx=await authorized(id);if(!ctx)return NextResponse.json({error:'Yetkiniz yok.'},{status:403});const{error}=await ctx.db.from('appointments').delete().eq('id',id);return error?NextResponse.json({error:'Silinemedi.'},{status:500}):NextResponse.json({ok:true})}
function whatsapp(ap:any,reason:string){let p=String(ap.customer_phone).replace(/\D/g,'');if(p.startsWith('0'))p='90'+p.slice(1);const text=`Merhaba ${ap.customer_first_name}, ${new Date(ap.start_at).toLocaleString('tr-TR',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Istanbul'})} tarihli ${ap.services?.name||''} randevunuz iptal edilmiştir. Neden: ${reason} — ${ap.businesses?.name||''}`;return`https://wa.me/${p}?text=${encodeURIComponent(text)}`}
async function sendCancellation(ap:any,reason:string){if(!process.env.RESEND_API_KEY||!ap.customer_email)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.NOTIFICATION_FROM,to:[ap.customer_email],subject:`${ap.businesses?.name||'Randevu'} — Randevu iptali`,html:`<h2>Randevunuz iptal edildi</h2><p>Merhaba ${ap.customer_first_name},</p><p><b>${ap.services?.name||''}</b> randevunuz işletme tarafından iptal edildi.</p><p><b>Neden:</b> ${reason}</p><p><b>Tarih:</b> ${new Date(ap.start_at).toLocaleString('tr-TR',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Istanbul'})}</p>`})}).catch(console.error)}
