import{NextRequest,NextResponse}from'next/server';import{createServiceClient}from'@/lib/supabase-server';import{z}from'zod';
const schema=z.object({businessId:z.string().uuid(),serviceId:z.string().uuid(),staffId:z.string().uuid().nullable().optional(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^\d{2}:\d{2}$/),firstName:z.string().trim().min(2).max(60),lastName:z.string().trim().min(2).max(60),phone:z.preprocess(v=>v==null?'':v,z.string().trim().min(10).max(25)),email:z.preprocess(v=>v==null?'':v,z.string().email().optional().or(z.literal(''))),note:z.preprocess(v=>v==null?'':v,z.string().max(500).optional())});
const iso=(d:string,t:string)=>`${d}T${t}:00+03:00`,hm=(v:string)=>{const[h,m]=v.slice(0,5).split(':').map(Number);return h*60+m};
export async function GET(req:NextRequest){const businessId=req.nextUrl.searchParams.get('businessId'),date=req.nextUrl.searchParams.get('date');if(!businessId||!date)return NextResponse.json({error:'Eksik bilgi'},{status:400});const db=createServiceClient(),from=iso(date,'00:00'),to=iso(date,'23:59'),[a,b]=await Promise.all([db.from('appointments').select('start_at,end_at,staff_id').eq('business_id',businessId).neq('status','cancelled').gte('start_at',from).lte('start_at',to),db.from('blocked_slots').select('start_at,end_at').eq('business_id',businessId).lt('start_at',to).gt('end_at',from)]);return NextResponse.json({busy:[...(a.data||[]),...(b.data||[])]},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:NextRequest){try{const x=schema.parse(await req.json()),db=createServiceClient(),[{data:biz},{data:service},{data:links}]=await Promise.all([db.from('businesses').select('*').eq('id',x.businessId).eq('is_published',true).single(),db.from('services').select('*').eq('id',x.serviceId).eq('business_id',x.businessId).eq('is_active',true).single(),db.from('staff_services').select('staff_id,staff_profiles!inner(is_active)').eq('service_id',x.serviceId)]);if(!biz||!service)return NextResponse.json({error:'İşletme veya hizmet bulunamadı.'},{status:404});let candidates=(links||[]).filter((l:any)=>l.staff_profiles?.is_active).map((l:any)=>l.staff_id);if(!candidates.length){const{data:fallback}=await db.from('staff_profiles').select('id').eq('business_id',x.businessId).eq('is_active',true);candidates=(fallback||[]).map(s=>s.id)}if(x.staffId)candidates=candidates.filter((id:string)=>id===x.staffId);if(!candidates.length)return NextResponse.json({error:'Bu hizmet için uygun çalışan yok.'},{status:400});
    if(!x.staffId&&candidates.length>1){
      const dayStart=new Date(`${x.date}T00:00:00+03:00`),dayEnd=new Date(`${x.date}T23:59:59+03:00`);
      const{data:todaysCounts}=await db.from('appointments').select('staff_id').in('staff_id',candidates).neq('status','cancelled').gte('start_at',dayStart.toISOString()).lte('start_at',dayEnd.toISOString());
      const countMap:Record<string,number>={};
      for(const c of candidates)countMap[c]=0;
      for(const row of todaysCounts||[])if(row.staff_id)countMap[row.staff_id]=(countMap[row.staff_id]||0)+1;
      candidates=[...candidates].sort((a,b)=>countMap[a]-countMap[b]);
    }
    const start=new Date(iso(x.date,x.time)),end=new Date(start.getTime()+service.duration_minutes*60000);if(start.getTime()<Date.now()+300000)return NextResponse.json({error:'Geçmiş saate randevu alınamaz.'},{status:400});const day=new Date(`${x.date}T12:00:00+03:00`).getDay(),chosen=hm(x.time);const{data:block}=await db.from('blocked_slots').select('id').eq('business_id',x.businessId).lt('start_at',end.toISOString()).gt('end_at',start.toISOString()).limit(1).maybeSingle();if(block)return NextResponse.json({error:'Bu saat kullanıma kapalı.'},{status:409});let selected:string|null=null;for(const sid of candidates){const[{data:wh},{data:conflict},{data:off}]=await Promise.all([db.from('staff_working_hours').select('*').eq('staff_id',sid).eq('day_of_week',day).maybeSingle(),db.from('appointments').select('id').eq('staff_id',sid).neq('status','cancelled').lt('start_at',end.toISOString()).gt('end_at',start.toISOString()).limit(1).maybeSingle(),db.from('staff_time_off').select('id').eq('staff_id',sid).eq('status','approved').lt('start_at',end.toISOString()).gt('end_at',start.toISOString()).limit(1).maybeSingle()]);if(wh?.is_open&&chosen>=hm(wh.start_time)&&chosen+service.duration_minutes<=hm(wh.end_time)&&!conflict&&!off){selected=sid;break}}if(!selected)return NextResponse.json({error:'Bu saatte uygun çalışan kalmadı.'},{status:409});const{data,error}=await db.from('appointments').insert({business_id:x.businessId,service_id:x.serviceId,staff_id:selected,customer_first_name:x.firstName,customer_last_name:x.lastName,customer_phone:x.phone,customer_email:x.email||null,customer_note:x.note||null,start_at:start.toISOString(),end_at:end.toISOString(),total_price:service.price,status:'confirmed'}).select('id,cancel_token').single();if(error)return NextResponse.json({error:'Bu saat az önce doldu.',_debug:{message:error.message,code:error.code,details:error.details,hint:error.hint}},{status:409});const site=process.env.NEXT_PUBLIC_SITE_URL||req.nextUrl.origin;return NextResponse.json({ok:true,id:data.id,cancelUrl:`${site}/randevu/${data.cancel_token}`},{status:201})}catch(e){if(e instanceof z.ZodError){const f=e.issues[0]?.path?.[0],names:Record<string,string>={firstName:'Ad',lastName:'Soyad',phone:'Telefon',email:'E-posta',note:'Not',date:'Tarih',time:'Saat'};return NextResponse.json({error:`${names[String(f)]||'Bilgileri'} kontrol edin.`},{status:400})}return NextResponse.json({error:'Beklenmeyen hata.'},{status:500})}}
