import TenantBooking from'@/components/TenantBooking';import GoogleReviews from'@/components/GoogleReviews';import OwnRatings from'@/components/OwnRatings';import'./radical-themes.css';
type P={b:any;services:any[];hours:any[];staff:any[];staffServices:any[];staffHours:any[];gallery:any[];media:any[]};
const SCHEME_COLORS:Record<string,{bg:string;text:string}>={light:{bg:'#f8f7f3',text:'#171717'},dark:{bg:'#0d0d0d',text:'#f6f2e9'},warm:{bg:'#f4eadb',text:'#39261d'},natural:{bg:'#eef3ea',text:'#243328'},soft:{bg:'#fff3f7',text:'#422531'},vivid:{bg:'#fff5df',text:'#27152c'},luxury:{bg:'#14110e',text:'#f2e3c5'}};
const FAMILY_DEFAULT_SCHEME:Record<string,string>={zen:'light',modern:'light',editorial:'light',vitrin:'dark',mega:'dark',prestij:'light',atolye:'light'};
export default function RadicalTenantSite(p:P){const family=(p.b.selected_theme_id||'barber_modern').split('_').at(-1),C:any={heritage:Heritage,modern:Modern,editorial:Editorial,soft:Soft,luxury:Luxury,pop:Pop,zen:Zen,fresh:Fresh,calm:Calm,cinematic:Cinematic,vitrin:Vitrin,mega:Mega,prestij:Prestij,atolye:Atolye},Layout=C[family]||Modern,cfg=p.b.published_site_config||{},mode=cfg.colorMode||'light',accent=accentHex(cfg.accentColor,p.b.primary_color),effectiveScheme=p.b.background_scheme&&p.b.background_scheme!=='theme_default'?p.b.background_scheme:(FAMILY_DEFAULT_SCHEME[family]||'light'),schemeColors=SCHEME_COLORS[effectiveScheme]||SCHEME_COLORS.light;return <div className={`radical profession-${p.b.business_type} mode-${mode} scheme-${effectiveScheme} cta-${p.b.cta_style||'solid'} cta-anim-${p.b.cta_animation||'none'}`} style={{'--accent':accent,'--brand':accent,'--bg':schemeColors.bg,'--text':schemeColors.text}as React.CSSProperties}><Layout {...p}/><WhatsApp b={p.b}/></div>}
const Brand=({b}:{b:any})=><a className="rBrand" href="#top">{b.logo_url?<img src={b.logo_url} alt={b.name}/>:<i>{b.name?.[0]}</i>}<b>{b.name}</b></a>;
const CTA=({b}:{b:any})=><a className="rCta" href="#randevu">{b.booking_button_text||'Randevu Al'} →</a>;
function ServiceList({p,variant='cards'}:{p:P;variant?:string}){return <section id="hizmetler" className={`rServices ${variant}`}><header><small>{p.b.services_label||'HİZMETLER'}</small><h2>{p.b.services_title||'Hizmetler'}</h2></header><div>{p.services.map((s,i)=><article key={s.id}><span>{String(i+1).padStart(2,'0')}</span><h3>{s.name}</h3>{s.description&&<p>{s.description}</p>}<footer><em>{s.duration_minutes} dk</em>{p.b.show_prices&&s.price!=null&&<b>{Number(s.price).toLocaleString('tr-TR')} ₺</b>}</footer></article>)}</div></section>}
function Staff({p,variant='grid'}:{p:P;variant?:string}){if(p.b.show_staff_section===false)return null;const visible=p.staff.filter(s=>!s.is_default&&s.is_active);if(!visible.length)return null;return <section className={`rStaff ${variant}`}><small>EKİBİMİZ</small><div>{visible.map(s=><article key={s.id}>{s.photo_url?<img src={s.photo_url} alt={s.name}/>:<i>{s.name[0]}</i>}<h3>{s.name}</h3><p>{s.title}</p></article>)}</div></section>}
function Gallery({p,variant='grid'}:{p:P;variant?:string}){const all=[...p.gallery.map(x=>({id:x.id,type:'image',url:x.image_url,alt:x.alt_text})),...p.media];if(!p.b.show_gallery||!all.length)return null;return <section className={`rGallery ${variant} media-count-${Math.min(all.length,6)} gallery-pos-${p.b.gallery_position||'after_services'} gallery-size-${p.b.gallery_size||'standard'} gallery-ratio-${p.b.gallery_ratio||'4_3'} gallery-mobile-${p.b.gallery_mobile_columns||'auto'}`}>{all.map(x=>x.type==='video'?<video key={x.id} src={x.url} controls playsInline preload="metadata"/>:<img key={x.id} src={x.url} alt={x.alt||p.b.name} loading="lazy"/>)}</section>}
function About({b}:{b:any}){if(!b.show_about||!b.description)return null;return <section className="rAbout"><small>{b.about_label||'HAKKIMIZDA'}</small><h2>{b.about_title||'Hakkımızda'}</h2><p>{b.description}</p></section>}
function Booking({p}:{p:P}){return <section id="randevu" className="rBooking"><header><small>{p.b.booking_label||'ONLINE RANDEVU'}</small><h2>{p.b.booking_title||'Saatini ayır.'}</h2></header><TenantBooking business={p.b} services={p.services} hours={p.hours} staff={p.staff} staffServices={p.staffServices} staffHours={p.staffHours}/></section>}
function Contact({b}:{b:any}){return <><GoogleReviews businessId={b.id}/><footer className="rContact"><Brand b={b}/><div><small>{b.address_label}</small><p>{b.address}</p></div><div><small>{b.phone_label}</small><p>{b.phone}</p></div><div><small>{b.instagram_label}</small><p>{b.instagram}</p></div></footer></>}
const HeroText=({b}:{b:any})=><><small>{b.hero_label}</small><h1>{b.hero_title||'Tarzını'}<em>{b.hero_highlight||''}</em></h1>{b.hero_description&&<p>{b.hero_description}</p>}<CTA b={b}/></>;
function Heritage(p:P){return <main id="top" className="tHeritage"><aside><Brand b={p.b}/><nav><a href="#hizmetler">Hizmetler</a><a href="#randevu">Randevu</a></nav>{dec(p.b,'line1','EST.')&&<b className="stamp"><span>{dec(p.b,'line1','EST.')}</span><span>{dec(p.b,'line2',String(p.b.established_year||''))}</span><span>{dec(p.b,'line3','')}</span></b>}</aside><div className="heritageBody"><section className="rHero"><HeroText b={p.b}/></section><ServiceList p={p} variant="ledger"/><About b={p.b}/><Staff p={p} variant="portraits"/><Gallery p={p} variant="framed"/><Booking p={p}/><Contact b={p.b}/></div></main>}
function Modern(p:P){return <main id="top" className="tModern"><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="rHero"><HeroText b={p.b}/></section><ServiceList p={p} variant="horizontal"/><Staff p={p} variant="rows"/><Gallery p={p} variant="strip"/><About b={p.b}/><Booking p={p}/><Contact b={p.b}/><OwnRatings businessId={p.b.id}/></main>}
function Editorial(p:P){return <main id="top" className="tEditorial"><header><Brand b={p.b}/></header><section className="rHero"><div><HeroText b={p.b}/></div></section><Gallery p={p} variant="editorial"/><div className="editorialColumns"><About b={p.b}/><ServiceList p={p} variant="article"/></div><Staff p={p} variant="magazine"/><Booking p={p}/><Contact b={p.b}/><OwnRatings businessId={p.b.id}/></main>}
function Soft(p:P){return <main id="top" className="tSoft"><header><Brand b={p.b}/><nav>Hizmetler　Galeri　<CTA b={p.b}/></nav></header><section className="rHero"><div className="softBlob"><HeroText b={p.b}/></div></section><Gallery p={p} variant="heroCollage"/><ServiceList p={p} variant="pills"/><Staff p={p} variant="bubbles"/><About b={p.b}/><Booking p={p}/><Contact b={p.b}/></main>}
function Luxury(p:P){return <main id="top" className="tLuxury"><header><Brand b={p.b}/>{dec(p.b,'kicker','PRIVATE APPOINTMENTS')&&<span>{dec(p.b,'kicker','PRIVATE APPOINTMENTS')}</span>}</header><section className="rHero"><div className="goldLine"/><HeroText b={p.b}/><div className="goldLine"/></section><Gallery p={p} variant="cinema"/><ServiceList p={p} variant="menu"/><Staff p={p} variant="luxury"/><About b={p.b}/><Booking p={p}/><Contact b={p.b}/><OwnRatings businessId={p.b.id}/></main>}
function Pop(p:P){return <main id="top" className="tPop"><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="popBento"><div className="rHero"><HeroText b={p.b}/></div>{dec(p.b,'line1','OPEN')&&<div className="popBadge"><span>{dec(p.b,'line1','OPEN')}</span><span>{dec(p.b,'line2','TODAY!')}</span></div>}</section><Gallery p={p} variant="popTile"/><ServiceList p={p} variant="stickers"/><Staff p={p} variant="bubbles"/><Booking p={p}/><About b={p.b}/><Contact b={p.b}/></main>}
function Zen(p:P){return <main id="top" className="tZen"><header><Brand b={p.b}/></header><section className="rHero"><HeroText b={p.b}/></section><About b={p.b}/><ServiceList p={p} variant="zenLines"/><Gallery p={p} variant="zenWide"/><Staff p={p} variant="zen"/><Booking p={p}/><Contact b={p.b}/><OwnRatings businessId={p.b.id}/></main>}
function Cinematic(p:P){return <main id="top" className="tCinematic"><header className="cNav"><Brand b={p.b}/><CTA b={p.b}/></header><section className="cHero" style={p.b.cover_url?{backgroundImage:`linear-gradient(180deg,#00000000 40%,#000000e6),url(${p.b.cover_url})`}:undefined}><div className="cHeroInner"><HeroText b={p.b}/></div></section><ServiceList p={p} variant="cinematicRows"/><Gallery p={p} variant="cinematicShowcase"/><Staff p={p} variant="cinematicPortrait"/><About b={p.b}/><Booking p={p}/><Contact b={p.b}/><OwnRatings businessId={p.b.id}/></main>}
function Vitrin(p:P){return <main id="top" className="tVitrin"><div className="vBar">🔥 {p.services.length} hizmet · Bugün müsait saatler var</div><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="rHero vHero"><HeroText b={p.b}/><div className="vBadgeRow"><span className="vBadge">⚡ Hızlı Randevu</span><span className="vBadge">★ {'★'.repeat(5)}</span></div></section><ServiceList p={p} variant="vitrinDeals"/><Gallery p={p} variant="vitrinGrid"/><Staff p={p} variant="row"/><Booking p={p}/><OwnRatings businessId={p.b.id}/><About b={p.b}/><Contact b={p.b}/></main>}
function Mega(p:P){return <main id="top" className="tMega"><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="megaHero"><HeroText b={p.b}/><div className="megaHeroStat"><b>{p.staff.length||1}</b><span>Uzman Kadro</span></div></section><div className="megaBento"><ServiceList p={p} variant="megaCards"/><Gallery p={p} variant="megaBig"/></div><Staff p={p} variant="megaScroll"/><Booking p={p}/><OwnRatings businessId={p.b.id}/><About b={p.b}/><Contact b={p.b}/></main>}
function Prestij(p:P){return <main id="top" className="tPrestij"><header className="pNav"><Brand b={p.b}/><CTA b={p.b}/></header><section className="pHero" style={p.b.cover_url?{backgroundImage:`linear-gradient(180deg,#00000010 40%,#000000d9),url(${p.b.cover_url})`}:undefined}><div className="pHeroInner"><HeroText b={p.b}/><div className="pStatRow"><div><b>5.0</b><span>Google Puanı</span></div><div><b>{p.b.address?.split(',')[0]||p.b.business_type}</b><span>Konum</span></div><div><b>Premium</b><span>Hizmet Kalitesi</span></div></div></div></section><section className="pFeatures"><div><span>✂</span><b>Uzman Ekip</b><small>Yılların deneyimi</small></div><div><span>✨</span><b>Premium Ürünler</b><small>En kaliteli markalar</small></div><div><span>◈</span><b>VIP Deneyim</b><small>Konforlu atmosfer</small></div><div><span>◷</span><b>Randevulu Sistem</b><small>Zamanınız değerli</small></div></section><ServiceList p={p} variant="prestijMenu"/><Gallery p={p} variant="prestijGrid"/><Staff p={p} variant="row"/><About b={p.b}/><Booking p={p}/><OwnRatings businessId={p.b.id}/><Contact b={p.b}/></main>}
function Atolye(p:P){return <main id="top" className="tAtolye"><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="aHero">{p.b.cover_url&&<div className="aHeroImg"><img src={p.b.cover_url} alt={p.b.name}/></div>}<div className="aHeroText"><HeroText b={p.b}/><div className="aStatStrip"><span>★ 5.0 Google Puanı</span><span>◈ Premium Hizmet</span><span>◷ Randevulu Çalışma</span></div></div></section><ServiceList p={p} variant="atolyeCards"/><Gallery p={p} variant="atolyeMasonry"/><Staff p={p} variant="row"/><About b={p.b}/><Booking p={p}/><OwnRatings businessId={p.b.id}/><Contact b={p.b}/></main>}
function Fresh(p:P){return <main id="top" className="tFresh"><header><Brand b={p.b}/><CTA b={p.b}/></header><section className="freshDashboard"><div className="rHero"><HeroText b={p.b}/></div><div className="freshStat"><b>7/24</b><span>Online Randevu</span></div><div className="freshStat"><b>{p.services.length}</b><span>Profesyonel Hizmet</span></div></section><ServiceList p={p} variant="info"/><div className="freshSplit"><Staff p={p}/><About b={p.b}/></div><Gallery p={p}/><Booking p={p}/><Contact b={p.b}/></main>}
function Calm(p:P){return <main id="top" className="tCalm"><header><Brand b={p.b}/><span>{dec(p.b,'topRight','Güvenli • Özel • Profesyonel')}</span></header><section className="rHero"><HeroText b={p.b}/></section><div className="calmReading"><About b={p.b}/><ServiceList p={p} variant="calmRows"/></div><Staff p={p} variant="private"/><Gallery p={p} variant="subtle"/><Booking p={p}/><Contact b={p.b}/></main>}
function WhatsApp({b}:{b:any}){if(!b.whatsapp_enabled)return null;let n=String(b.whatsapp_phone||b.phone||'').replace(/\D/g,'');if(n.startsWith('0'))n='90'+n.slice(1);return n?<a className="rWhatsapp" href={`https://wa.me/${n}?text=${encodeURIComponent(b.whatsapp_message||'Merhaba')}`}>WhatsApp</a>:null}
function accentHex(name:string,fallback:string){return({black:'#111111',burgundy:'#7c3157',pink:'#ed5da8',purple:'#7652a6',sage:'#6f8f78',blue:'#71849c',orange:'#d8753f',gold:'#9b7b3f'}as any)[name]||fallback||'#111111'}

function dec(b:any,key:string,fallback:string){const d=b.theme_decorations||{};return Object.prototype.hasOwnProperty.call(d,key)?d[key]:fallback}
